var $jscomp={scope:{},findInternal:function(d,a,b){d instanceof String&&(d=String(d));for(var c=d.length,e=0;e<c;e++){var g=d[e];if(a.call(b,g,e,d))return{i:e,v:g}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(d,a,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");d!=Array.prototype&&d!=Object.prototype&&(d[a]=b.value)};
$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(d,a,b,c){if(a){b=$jscomp.global;d=d.split(".");for(c=0;c<d.length-1;c++){var e=d[c];e in b||(b[e]={});b=b[e]}d=d[d.length-1];c=b[d];a=a(c);a!=c&&null!=a&&$jscomp.defineProperty(b,d,{configurable:!0,writable:!0,value:a})}};
$jscomp.polyfill("Array.prototype.find",function(d){return d?d:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6-impl","es3");
!function(d){d.fn.slide=function(a){return d.fn.slide.defaults={type:"slide",effect:"fade",autoPlay:!1,delayTime:500,interTime:2500,triggerTime:150,defaultIndex:0,titCell:".hd li",mainCell:".bd",targetCell:null,trigger:"mouseover",scroll:1,vis:1,titOnClassName:"on",autoPage:!1,prevCell:".prev",nextCell:".next",pageStateCell:".pageState",opp:!1,pnLoop:!0,easing:"swing",startFun:null,endFun:null,switchLoad:null,playStateCell:".playState",mouseOverStop:!0,defaultPlay:!0,returnDefault:!1},this.each(function(){var b=
d.extend({},d.fn.slide.defaults,a),c=d(this),e=b.effect,g=d(b.prevCell,c),n=d(b.nextCell,c),ha=d(b.pageStateCell,c),J=d(b.playStateCell,c),q=d(b.titCell,c),k=q.size(),h=d(b.mainCell,c),l=h.children().size(),B=b.switchLoad,F=d(b.targetCell,c),f=parseInt(b.defaultIndex),r=parseInt(b.delayTime),T=parseInt(b.interTime);parseInt(b.triggerTime);var y,m=parseInt(b.scroll),w=parseInt(b.vis),M="false"==b.autoPlay||0==b.autoPlay?!1:!0,U="false"==b.opp||0==b.opp?!1:!0,t="false"==b.autoPage||0==b.autoPage?!1:
!0,N="false"==b.pnLoop||0==b.pnLoop?!1:!0,V="false"==b.mouseOverStop||0==b.mouseOverStop?!1:!0,K="false"==b.defaultPlay||0==b.defaultPlay?!1:!0,H="false"==b.returnDefault||0==b.returnDefault?!1:!0,v=0,u=0,L=0,O=0,z=b.easing,G=null,P=null,Q=null,C=b.titOnClassName,x=q.index(c.find("."+C)),W=f=-1==x?f:x,ca=f,I=f,p=l>=w?0!=l%m?l%m:m:0,D="leftMarquee"==e||"topMarquee"==e?!0:!1,da=function(){d.isFunction(b.startFun)&&b.startFun(f,k,c,d(b.titCell,c),h,F,g,n)},A=function(){d.isFunction(b.endFun)&&b.endFun(f,
k,c,d(b.titCell,c),h,F,g,n)},X=function(){q.removeClass(C);K&&q.eq(ca).addClass(C)};if("menu"==b.type)return K&&q.removeClass(C).eq(f).addClass(C),q.hover(function(){y=d(this).find(b.targetCell);var a=q.index(d(this));P=setTimeout(function(){switch(f=a,q.removeClass(C).eq(f).addClass(C),da(),e){case "fade":y.stop(!0,!0).animate({opacity:"show"},r,z,A);break;case "slideDown":y.stop(!0,!0).animate({height:"show"},r,z,A)}},b.triggerTime)},function(){switch(clearTimeout(P),e){case "fade":y.animate({opacity:"hide"},
r,z);break;case "slideDown":y.animate({height:"hide"},r,z)}}),H&&c.hover(function(){clearTimeout(Q)},function(){Q=setTimeout(X,r)}),void 0;if(0==k&&(k=l),D&&(k=2),t){l>=w?"leftLoop"==e||"topLoop"==e?k=0!=l%m?(0^l/m)+1:l/m:(t=l-w,k=1+parseInt(0!=t%m?t/m+1:t/m),0>=k&&(k=1)):k=1;q.html("");t="";if(1==b.autoPage||"true"==b.autoPage)for(x=0;k>x;x++)t+="<li>"+(x+1)+"</li>";else for(x=0;k>x;x++)t+=b.autoPage.replace("$",x+1);q.html(t);q=q.children()}if(l>=w){h.children().each(function(){d(this).width()>
L&&(L=d(this).width(),u=d(this).outerWidth(!0));d(this).height()>O&&(O=d(this).height(),v=d(this).outerHeight(!0))});var ea=h.children(),t=function(){for(var a=0;w>a;a++)ea.eq(a).clone().addClass("clone").appendTo(h);for(a=0;p>a;a++)ea.eq(l-a-1).clone().addClass("clone").prependTo(h)};switch(e){case "fold":h.css({position:"relative",width:u,height:v}).children().css({position:"absolute",width:L,left:0,top:0,display:"none"});break;case "top":h.wrap('<div class="tempWrap" style="overflow:hidden; position:relative; height:'+
w*v+'px"></div>').css({top:-(f*m)*v,position:"relative",padding:"0",margin:"0"}).children().css({height:O});break;case "left":h.wrap('<div class="tempWrap" style="overflow:hidden; position:relative; width:'+w*u+'px"></div>').css({width:l*u,left:-(f*m)*u,position:"relative",overflow:"hidden",padding:"0",margin:"0"}).children().css({"float":"left",width:L});break;case "leftLoop":case "leftMarquee":t();h.wrap('<div class="tempWrap" style="overflow:hidden; position:relative; width:'+w*u+'px"></div>').css({width:(l+
w+p)*u,position:"relative",overflow:"hidden",padding:"0",margin:"0",left:-(p+f*m)*u}).children().css({"float":"left",width:L});break;case "topLoop":case "topMarquee":t(),h.wrap('<div class="tempWrap" style="overflow:hidden; position:relative; height:'+w*v+'px"></div>').css({height:(l+w+p)*v,position:"relative",padding:"0",margin:"0",top:-(p+f*m)*v}).children().css({height:O})}}var Y=function(a){var b=a*m;return a==k?b=l:-1==a&&0!=l%m&&(b=-l%m),b},fa=function(a){var b=function(b){for(var c=b;w+b>c;c++)a.eq(c).find("img["+
B+"]").each(function(){var a=d(this);if(a.attr("src",a.attr(B)).removeAttr(B),h.find(".clone")[0])for(var b=h.children(),c=0;c<b.size();c++)b.eq(c).find("img["+B+"]").each(function(){d(this).attr(B)==a.attr("src")&&d(this).attr("src",d(this).attr(B)).removeAttr(B)})})};switch(e){case "fade":case "fold":case "top":case "left":case "slideDown":b(f*m);break;case "leftLoop":case "topLoop":b(p+Y(I));break;case "leftMarquee":case "topMarquee":var c="leftMarquee"==e?h.css("left").replace("px",""):h.css("top").replace("px",
""),g="leftMarquee"==e?u:v,k=p;0!=c%g&&(c=Math.abs(0^c/g),k=1==f?p+c:p+c-1);b(k)}},E=function(a){if(!K||W!=f||a||D){if(D?1<=f?f=1:0>=f&&(f=0):(I=f,f>=k?f=0:0>f&&(f=k-1)),da(),null!=B&&fa(h.children()),F[0]&&(y=F.eq(f),null!=B&&fa(F),"slideDown"==e?(F.not(y).stop(!0,!0).slideUp(r),y.slideDown(r,z,function(){h[0]||A()})):(F.not(y).stop(!0,!0).hide(),y.animate({opacity:"show"},r,function(){h[0]||A()}))),l>=w)switch(e){case "fade":h.children().stop(!0,!0).eq(f).animate({opacity:"show"},r,z,function(){A()}).siblings().hide();
break;case "fold":h.children().stop(!0,!0).eq(f).animate({opacity:"show"},r,z,function(){A()}).siblings().animate({opacity:"hide"},r,z);break;case "top":h.stop(!0,!1).animate({top:-f*m*v},r,z,function(){A()});break;case "left":h.stop(!0,!1).animate({left:-f*m*u},r,z,function(){A()});break;case "leftLoop":var b=I;h.stop(!0,!0).animate({left:-(Y(I)+p)*u},r,z,function(){-1>=b?h.css("left",-(p+(k-1)*m)*u):b>=k&&h.css("left",-p*u);A()});break;case "topLoop":b=I;h.stop(!0,!0).animate({top:-(Y(I)+p)*v},
r,z,function(){-1>=b?h.css("top",-(p+(k-1)*m)*v):b>=k&&h.css("top",-p*v);A()});break;case "leftMarquee":a=h.css("left").replace("px","");0==f?h.animate({left:++a},0,function(){0<=h.css("left").replace("px","")&&h.css("left",-l*u)}):h.animate({left:--a},0,function(){h.css("left").replace("px","")<=-(l+p)*u&&h.css("left",-p*u)});break;case "topMarquee":a=h.css("top").replace("px",""),0==f?h.animate({top:++a},0,function(){0<=h.css("top").replace("px","")&&h.css("top",-l*v)}):h.animate({top:--a},0,function(){h.css("top").replace("px",
"")<=-(l+p)*v&&h.css("top",-p*v)})}q.removeClass(C).eq(f).addClass(C);W=f;N||(n.removeClass("nextStop"),g.removeClass("prevStop"),0==f&&g.addClass("prevStop"),f==k-1&&n.addClass("nextStop"));ha.html("<span>"+(f+1)+"</span>/"+k)}};K&&E(!0);H&&c.hover(function(){clearTimeout(Q)},function(){Q=setTimeout(function(){f=ca;K?E():"slideDown"==e?y.slideUp(r,X):y.animate({opacity:"hide"},r,X);W=f},300)});var Z=function(a){G=setInterval(function(){U?f--:f++;E()},a?a:T)},R=function(a){G=setInterval(E,a?a:T)},
S=function(){V||(clearInterval(G),Z())},H=function(){(N||f!=k-1)&&(f++,E(),D||S())},t=function(){(N||0!=f)&&(f--,E(),D||S())},aa=function(){clearInterval(G);D?R():Z();J.removeClass("pauseState")},ba=function(){clearInterval(G);J.addClass("pauseState")};if(M?D?(U?f--:f++,R(),V&&h.hover(ba,aa)):(Z(),V&&c.hover(ba,aa)):(D&&(U?f--:f++),J.addClass("pauseState")),J.click(function(){J.hasClass("pauseState")?aa():ba()}),"mouseover"==b.trigger?q.hover(function(){var a=q.index(this);P=setTimeout(function(){f=
a;E();S()},b.triggerTime)},function(){clearTimeout(P)}):q.click(function(){f=q.index(this);E();S()}),D){if(n.mousedown(H),g.mousedown(t),N){var ga,M=function(){ga=setTimeout(function(){clearInterval(G);R(0^T/10)},150)},x=function(){clearTimeout(ga);clearInterval(G);R()};n.mousedown(M);n.mouseup(x);g.mousedown(M);g.mouseup(x)}"mouseover"==b.trigger&&(n.hover(H,function(){}),g.hover(t,function(){}))}else n.click(H),g.click(t)})}}(jQuery);jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(d,a,b,c,e){return jQuery.easing[jQuery.easing.def](d,a,b,c,e)},easeInQuad:function(d,a,b,c,e){return c*(a/=e)*a+b},easeOutQuad:function(d,a,b,c,e){return-c*(a/=e)*(a-2)+b},easeInOutQuad:function(d,a,b,c,e){return 1>(a/=e/2)?c/2*a*a+b:-c/2*(--a*(a-2)-1)+b},easeInCubic:function(d,a,b,c,e){return c*(a/=e)*a*a+b},easeOutCubic:function(d,a,b,c,e){return c*((a=a/e-1)*a*a+1)+b},easeInOutCubic:function(d,a,b,c,e){return 1>(a/=e/2)?c/2*a*a*a+b:
c/2*((a-=2)*a*a+2)+b},easeInQuart:function(d,a,b,c,e){return c*(a/=e)*a*a*a+b},easeOutQuart:function(d,a,b,c,e){return-c*((a=a/e-1)*a*a*a-1)+b},easeInOutQuart:function(d,a,b,c,e){return 1>(a/=e/2)?c/2*a*a*a*a+b:-c/2*((a-=2)*a*a*a-2)+b},easeInQuint:function(d,a,b,c,e){return c*(a/=e)*a*a*a*a+b},easeOutQuint:function(d,a,b,c,e){return c*((a=a/e-1)*a*a*a*a+1)+b},easeInOutQuint:function(d,a,b,c,e){return 1>(a/=e/2)?c/2*a*a*a*a*a+b:c/2*((a-=2)*a*a*a*a+2)+b},easeInSine:function(d,a,b,c,e){return-c*Math.cos(a/
e*(Math.PI/2))+c+b},easeOutSine:function(d,a,b,c,e){return c*Math.sin(a/e*(Math.PI/2))+b},easeInOutSine:function(d,a,b,c,e){return-c/2*(Math.cos(Math.PI*a/e)-1)+b},easeInExpo:function(d,a,b,c,e){return 0==a?b:c*Math.pow(2,10*(a/e-1))+b},easeOutExpo:function(d,a,b,c,e){return a==e?b+c:c*(-Math.pow(2,-10*a/e)+1)+b},easeInOutExpo:function(d,a,b,c,e){return 0==a?b:a==e?b+c:1>(a/=e/2)?c/2*Math.pow(2,10*(a-1))+b:c/2*(-Math.pow(2,-10*--a)+2)+b},easeInCirc:function(d,a,b,c,e){return-c*(Math.sqrt(1-(a/=e)*
a)-1)+b},easeOutCirc:function(d,a,b,c,e){return c*Math.sqrt(1-(a=a/e-1)*a)+b},easeInOutCirc:function(d,a,b,c,e){return 1>(a/=e/2)?-c/2*(Math.sqrt(1-a*a)-1)+b:c/2*(Math.sqrt(1-(a-=2)*a)+1)+b},easeInElastic:function(d,a,b,c,e){d=0;var g=c;if(0==a)return b;if(1==(a/=e))return b+c;(d||(d=.3*e),g<Math.abs(c))?(g=c,c=d/4):c=d/(2*Math.PI)*Math.asin(c/g);return-(g*Math.pow(2,10*--a)*Math.sin(2*(a*e-c)*Math.PI/d))+b},easeOutElastic:function(d,a,b,c,e){var g=0,n=c;if(0==a)return b;if(1==(a/=e))return b+c;(g||
(g=.3*e),n<Math.abs(c))?(n=c,d=g/4):d=g/(2*Math.PI)*Math.asin(c/n);return n*Math.pow(2,-10*a)*Math.sin(2*(a*e-d)*Math.PI/g)+c+b},easeInOutElastic:function(d,a,b,c,e){var g=0,n=c;if(0==a)return b;if(2==(a/=e/2))return b+c;(g||(g=.3*e*1.5),n<Math.abs(c))?(n=c,d=g/4):d=g/(2*Math.PI)*Math.asin(c/n);return 1>a?-.5*n*Math.pow(2,10*--a)*Math.sin(2*(a*e-d)*Math.PI/g)+b:.5*n*Math.pow(2,-10*--a)*Math.sin(2*(a*e-d)*Math.PI/g)+c+b},easeInBack:function(d,a,b,c,e,g){return void 0==g&&(g=1.70158),c*(a/=e)*a*((g+
1)*a-g)+b},easeOutBack:function(d,a,b,c,e,g){return void 0==g&&(g=1.70158),c*((a=a/e-1)*a*((g+1)*a+g)+1)+b},easeInOutBack:function(d,a,b,c,e,g){return void 0==g&&(g=1.70158),1>(a/=e/2)?c/2*a*a*(((g*=1.525)+1)*a-g)+b:c/2*((a-=2)*a*(((g*=1.525)+1)*a+g)+2)+b},easeInBounce:function(d,a,b,c,e){return c-jQuery.easing.easeOutBounce(d,e-a,0,c,e)+b},easeOutBounce:function(d,a,b,c,e){return(a/=e)<1/2.75?7.5625*c*a*a+b:2/2.75>a?c*(7.5625*(a-=1.5/2.75)*a+.75)+b:2.5/2.75>a?c*(7.5625*(a-=2.25/2.75)*a+.9375)+b:
c*(7.5625*(a-=2.625/2.75)*a+.984375)+b},easeInOutBounce:function(d,a,b,c,e){return e/2>a?.5*jQuery.easing.easeInBounce(d,2*a,0,c,e)+b:.5*jQuery.easing.easeOutBounce(d,2*a-e,0,c,e)+.5*c+b}});
